### Vector Visualization

In [3]:
import numpy as np 
import matplotlib.pyplot as plt
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
print("Vector Addition:",vector1 + vector2)
print("Vector Multiplication:",vector1 * vector2)
v1=np.array([[1,2],[3,4]])
v2=np.array([[6,7]])
print("Matrix multiplication:\n",v1*v2)
print("Dot product:",np.dot(vector1,vector2))
angle=np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print("Angle between two vector:",angle)




Vector Addition: [ 7  9 11 13 15]
Vector Multiplication: [ 6 14 24 36 50]
Matrix multiplication:
 [[ 6 14]
 [18 28]]
Dot product: 130
Angle between two vector: 0.26554161733900966


### Vectorized Operation

In [10]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.random.rand(3,3)
array3=np.zeros((4,4))
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [11]:
loaded_array1=np.load('array1.npy')
print(loaded_array1)


[[1 2 3]
 [4 5 6]]


In [21]:

"""try:
    logo = np.load('numpy-logo.npy')
    # Display the logo
    plt.figure(figsize=(10,5))
    plt.subplot(121)
    # np.save("numpy-logo.npy", logo)
    plt.imshow(logo)
    plt.title("Numpy Logo")
    plt.grid(False)
    # plt.show()
    dark_mode=1-logo
    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.title("Numpy Dark Logo")
    plt.grid(False)
except FileNotFoundError:
    print("Numpy logo not found !!")
    """

'try:\n    logo = np.load(\'numpy-logo.npy\')\n    # Display the logo\n    plt.figure(figsize=(10,5))\n    plt.subplot(121)\n    # np.save("numpy-logo.npy", logo)\n    plt.imshow(logo)\n    plt.title("Numpy Logo")\n    plt.grid(False)\n    # plt.show()\n    dark_mode=1-logo\n    plt.subplot(122)\n    plt.imshow(dark_logo)\n    plt.title("Numpy Dark Logo")\n    plt.grid(False)\nexcept FileNotFoundError:\n    print("Numpy logo not found !!")\n    '