# Creating Array from List

In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4,5,6])
print("1D array:",arr_1d)

1D array: [1 2 3 4 5 6]


In [3]:
arr_2d=np.array([[1,2,3],[3,4,5],[5,6,7]])
print("2D array:\n",arr_2d)

2D array:
 [[1 2 3]
 [3 4 5]
 [5 6 7]]


### list vs numpy array

#### list just duplicate it n times but numpy arr exactly multiply element wise

In [4]:
pyList=[1,2,3,5,4]
print("Python list multiplication:\n ",pyList*2)  # it just duplicate it 2 times

Python list multiplication:
  [1, 2, 3, 5, 4, 1, 2, 3, 5, 4]


In [5]:
npArr=np.array([1,2,3])

In [6]:
print("Python Array multipliction:\n",npArr*2)  # it perform element wise multiplication

Python Array multipliction:
 [2 4 6]


In [7]:
import time as tm
start=tm.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time:",tm.time()-start)


 List operation time: 0.4822220802307129


In [8]:
start=tm.time()
np.array=np.arange(1000000)*2
print("\n Numpy operation time:",tm.time()-start)


 Numpy operation time: 0.022936344146728516


### creating zeros from scratch

In [9]:
import numpy as np
zeros=np.zeros((3,3))
print("Zeros array:\n",zeros)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones=np.ones((4,3))
print("Ones Array:\n",ones)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full=np.full((5,4),5)
print("full array:\n",full)

full array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
sequence=np.arange(0,11,2)
print("Sequence Array:\n",sequence)
print("Sequence Array:\n",sequence*2)


Sequence Array:
 [ 0  2  4  6  8 10]
Sequence Array:
 [ 0  4  8 12 16 20]


### Vector , matrix and Tensor

In [ ]:
import numpy as nmp
vector=nmp.array([3,9,1])
print("Vector:",vector)

Vector: [3 9 1]


In [ ]:
matrix=nmp.array([[1,2,3],
                  [4,5,6]])
print("Matrix:\n",matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


In [ ]:
tensor=nmp.array([[[1,2,3],[3,4,5]],
                  [[5,6,7],[7,8,9]]])
print("tensor:\n",tensor)

tensor:
 [[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


### Array Properties:

In [ ]:
arr=nmp.array([[1,2,3],
               [4,5,6],
               [0,0,0]])
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("DataType:",arr.dtype)

Shape: (3, 3)
Dimension: 2
Size: 9
DataType: int64


### Array Reshaping

In [ ]:
Arr=nmp.arange(12)
print("Original Array:",Arr)
reshaped=Arr.reshape((3,4))
print("Reshaped Array:\n",reshaped)
flatten=reshaped.flatten() # flatten method rechanged in linear manner
print("flatten Array:",flatten)
# ravel (returns view , instead of copy) just like as flattten in linear manner
raveled=reshaped.ravel()
print("Raveled Array:",raveled)
# transpose the matrix using properties arr.T
transpose=reshaped.T
print("Transpose matrix:\n",transpose)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
random=nmp.random.random((2,3))
print("Random array:\n",random)
print("Random array:\n",random*10)