In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing:",arr[2:7])
print("Slicing with steps:",arr[1:9:3])
print("Negative Index:",arr[-3])
print("Negative Index:",arr[-3:])

Basic Slicing: [3 4 5 6 7]
Slicing with steps: [2 5 8]
Negative Index: 7
Negative Index: [7 8 9]


### 2D Array Slicing

In [ ]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Entire first Row:",arr_2d[0]) # first row
print("Entire second Row:",arr_2d[1]) # Second row
print("Specific Element:",arr_2d[0,2]) #specific element
# print("Speciic not found element:",arr_2d[1,5]) this will gives error
"""   to find entire columns   """
print("Entire column:",arr_2d[:, 2])   # [3,6,9]

Entire first Row: [1 2 3]
Entire second Row: [4 5 6]
Specific Element: 3
Entire column: [3 6 9]


### Sorting 2D Array

In [ ]:
unsorted=np.array([1,2,8,9,4,30,5,1,2])
print("Sorted Array:",np.sort((unsorted)))
 
arr_2d_unsorted=np.array([[1,2,3],
                          [9,8,7],
                          [2,5,6]])
#  0 -> column-wise    and  1 -> row-wise
print("2D Array Sorting by cloumn:\n",np.sort(arr_2d_unsorted,axis=0))
print("2D Array Sorting by rows:\n",np.sort(arr_2d_unsorted,axis=1))

Sorted Array: [ 1  1  2  2  4  5  8  9 30]
2D Array Sorting by cloumn:
 [[1 2 3]
 [2 5 6]
 [9 8 7]]
2D Array Sorting by rows:
 [[1 2 3]
 [7 8 9]
 [2 5 6]]


### Filter

In [ ]:
numbers=np.arange(11)
even_numbers=numbers[numbers % 2 == 0]
print("Even Numbers:",even_numbers)

Even Numbers: [ 0  2  4  6  8 10]


### Filter with mask 

In [ ]:
mask=numbers>5
print("Numbers greater than 5:",numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [32]:
# print(numbers)
indices=[0,2,6]
print(numbers[indices])

[0 2 6]


In [33]:
where_result=np.where(numbers>5)
print(where_result)
print("Np where:",numbers[where_result])

(array([ 6,  7,  8,  9, 10]),)
Np where: [ 6  7  8  9 10]


In [ ]:
condition=np.where(numbers>5,numbers*2,numbers)
print(condition)

[ 0  1  2  3  4  5 12 14 16 18 20]


### Adding and Removing data

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=arr1+arr2
concatenatedArr=np.concatenate((arr1,arr2))
print("Adding corresponding elements of Array:",combined)
print("Concating two array:",concatenatedArr)
"""   Deleting array element using delete() methods """
deleted1=np.delete(arr1,0) # 0 means it's index
deleted2=np.delete(arr2,2)
print("deleted1 after deletion:",deleted1)
print("deleted2 after deletion:",deleted2)

Adding corresponding elements of Array: [5 7 9]
Concating two array: [1 2 3 4 5 6]
deleted1 after deletion: [2 3]
deleted2 after deletion: [4 5]


### Compatibility shapes (True or False)

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,2,6,8,9,4])
arr3=np.array([2,3,4,0])
print("Compability shapes:",arr1.shape==arr3.shape) # True
print("Compatability shapes:",arr1.shape==arr2.shape) # False

Compability shapes: True
Compatability shapes: False


### Adding new rows and columns in existing array using vstack and hstack

In [50]:
original=np.array([[1,2],
                   [4,5]])
new_row=np.array([[7,9]])
print("Original Array:\n",original)
print("********* Adding new rows  similar to the append  ********")
print(" vtack method used to add entire row")
print("Array after adding new row:\n",np.vstack((original,new_row)))
print("********* Adding new rows  similar to the append  ********")
new_col=np.array([[10],[9]])
print(" htack method used to add entire column.")
print("Array after adding new columns:\n",np.hstack((original,new_col)))

Original Array:
 [[1 2]
 [4 5]]
********* Adding new rows  similar to the append  ********
 vtack method used to add entire row
Array after adding new row:
 [[1 2]
 [4 5]
 [7 9]]
********* Adding new rows  similar to the append  ********
 htack method used to add entire column.
Array after adding new columns:
 [[ 1  2 10]
 [ 4  5  9]]
